# -*- coding: utf-8 -*-
"""multiprocessing_new(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFBSn6nrt5L2Fzv2rP4GtEdEmiZ1jutY
"""

import os
import time
from multiprocessing import Process, Manager

def compute_gwa_mp(name, grades, results_list):
    """
    Calculates the average for a student and stores it in the shared list.
    """
    if not grades:
        gwa = 0.0
    else:
        gwa = sum(grades) / len(grades)

    # Simulate a small delay for processing
    time.sleep(0.5)

    # Store the result in the shared manager list
    results_list.append(f"Student: {name:10} | GWA: {gwa:.2f} | PID: {os.getpid()}")

if __name__ == "__main__":
    # --- 1. DATA COLLECTION ---
    students_data = {}
    print("=== Student Grade Entry (Multiprocessing Only) ===")

    try:
        num_students = int(input("How many students? "))
        for i in range(num_students):
            name = input(f"Name for student {i+1}: ")
            raw_grades = input(f"Grades for {name} (space-separated): ")
            students_data[name] = [float(g) for g in raw_grades.split()]
    except ValueError:
        print("\n[!] Invalid input. Using defaults.")
        students_data = {"Alice": [85, 90], "Bob": [70, 80]}

    print(f"\n[System] Spawning {len(students_data)} processes...")
    print("-" * 50)

    # --- 2. MULTIPROCESSING EXECUTION ---
    start_time = time.perf_counter()

    # 'Manager' allows processes to share information back to the main script
    with Manager() as manager:
        shared_results = manager.list()
        processes = []

        for name, grades in students_data.items():
            # Create a process for each student
            p = Process(target=compute_gwa_mp, args=(name, grades, shared_results))
            processes.append(p)
            p.start()

        # Wait for all processes to finish
        for p in processes:
            p.join()

        # Record end time
        execution_time = time.perf_counter() - start_time

        # --- 3. OUTPUT RESULTS ---
        for result in shared_results:
            print(f"[Done] {result}")

    print("-" * 50)
    print(f"Total Multiprocessing Execution Time: {execution_time:.6f} seconds")